# Generated by Django 5.1.7 on 2025-03-24 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_remove_vehicle_current_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
