# Generated by Django 5.1.7 on 2025-04-09 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_vehicle_alter_product_vehicle'),
        ('tracking', '0003_alter_vehicle_latitude_alter_vehicle_longitude'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vehicle',
        ),
    ]
