# Generated by Django 5.1.7 on 2025-03-24 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_vehicle_latitude_alter_vehicle_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='longitude',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='current_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
