# Generated by Django 5.1.7 on 2025-03-24 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_vehicle_latitude_remove_vehicle_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='long',
            field=models.FloatField(null=True),
        ),
    ]
