# Generated by Django 5.1.7 on 2025-04-09 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_vehicle_lat_vehicle_long'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vehicle',
        ),
    ]
