# Generated by Django 5.1.7 on 2025-03-20 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rfid_tag', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('stored', 'Stored'), ('in_transit', 'In Transit'), ('delivered', 'Delivered')], default='stored', max_length=20)),
                ('warehouse_location', models.CharField(blank=True, max_length=255, null=True)),
                ('last_scanned_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
