# Generated by Django 5.1.7 on 2025-04-15 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_vehicle_alter_product_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
