# Generated by Django 5.1.7 on 2025-04-27 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_vehicle_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='id',
            new_name='plate_number',
        ),
        migrations.AddField(
            model_name='product',
            name='receiver_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='receiver_phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
