# Generated by Django 5.1.7 on 2025-04-27 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_rename_id_vehicle_plate_number_product_receiver_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='lat',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='long',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
    ]
