# Generated by Django 5.1.7 on 2025-04-27 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_vehicle_lat_alter_vehicle_long'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='status',
        ),
    ]
