# Generated by Django 5.1.7 on 2025-06-23 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_product_identification_method_product_qr_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='identification_method',
        ),
        migrations.RemoveField(
            model_name='product',
            name='qr_code',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ticket',
        ),
        migrations.AddField(
            model_name='product',
            name='receiver_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
