# Generated by Django 5.1.7 on 2025-06-23 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_remove_product_identification_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='identification_method',
            field=models.CharField(choices=[('rfid', 'RFID'), ('qr code', 'QR Code')], default='rfid', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='qr_code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ticket',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ticket_pdf',
            field=models.FileField(blank=True, null=True, upload_to='tickets/'),
        ),
    ]
