# Generated by Django 5.1.7 on 2025-06-23 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_product_identification_method_product_qr_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rfid_tag',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
